services:
  slot:
    container_name: slot
    image: xixi4den/ma.slot-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__MA=Debug
      - Redis__ConnectionString=redis-slot
      - Rabbit__Host=rabbitmq
      - Rabbit__Username=guest
      - Rabbit__Password=guest
      - EXPORTER_OTLP_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - 8081:80
    depends_on:
      redis-slot:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_started

  redis-slot:
    container_name: redis-slot
    image: redis/redis-stack-server:latest

  reward:
    container_name: reward
    image: xixi4den/ma.reward-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__MA=Debug
      - Redis__ConnectionString=redis-slot
      - Rabbit__Host=rabbitmq
      - Rabbit__Username=guest
      - Rabbit__Password=guest
      - Missions__FilePath=/opt/reward/config/missions-config.json
      - EXPORTER_OTLP_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - 8082:80
    volumes:
      - type: bind
        source: ./config
        target: /opt/reward/config
    depends_on:
      redis-reward:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_started

  redis-reward:
    container_name: redis-reward
    image: redis/redis-stack-server:latest

  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq:latest
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
